### ISSUE TITLE
Should we add requiresafe as a pre-commit?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#10]
https://requiresafe.com/

**Comment by iteles** [comment]
I assume dependencies would certainly be vetted in more detail security-wise by ^lift than by the bithound guys!

Should we give it another couple of months to see if there's some regular work on it (seeing as it's currently a side project from what I can see)? There don't appear to have been any updates since it's [April release](https://requiresafe.com/releases).

**Comment by nelsonic** [comment]
https://nodesecurity.io/
