### ISSUE TITLE
Why Hapi?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#35]
Why Hapi?

Why do we use Hapi.js instead of (_more popular_) "Framework-JS"...?

https://github.com/dwyl?utf8=%E2%9C%93&q=hapi

Relates to: Why Node.js ...?

**Comment by Charlotteis** [comment]
Might be cool to compare it with 'express.js'.

**Comment by nelsonic** [comment]
@Charlotteis Agree 100%. (_a comparison between Hapi & Express is **essential**_! CC: @esraajb 😉 )
This post by @starefossen: https://starefossen.github.io/post/2016/02/13/nodejs-drama-express
pretty much sums up ***why*** we **stopped _using_ Express** (_and switched to Hapi_)
Express is/was _really_ good from a technical perspective. We _used+ it for both work & personal projects for a while... but when StrongLoop _Bought_ it in 2014 it was our "_signal_" to consider alternatives...
We found hapi through @nvcexploder and we were immediately drawn into it's community-focus, standards-compliance, ease-of-use (_beginner friendliness_) and rigorous approach to both reliability and performance! 😍 

Also, it doesn't _hurt_ that Hapi has testing/mocking _built-in_ with ["shot"](https://www.npmjs.com/package/shot) (_which makes **testing** [***#easy***](https://youtu.be/at3FPJaAwoY) and thus **reliability** a core-focus of all our apps..._), 
a much nicer plugin architecture with "hooks" which we find easier to debug than express' "middleware" (_which are simpler but not necessarily better_),
and there are no "spanners" in the stack. https://medium.com/friendship-dot-js/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558 😉 

@Charlotteis what is **_your_ experience**...? 
You use/maintain [Hoodie](https://github.com/hoodiehq/hoodie) which uses Hapi _under-the-hood_ (_pun intended_), but you've also tried the "_alternatives_" ... 
What were the Pros/Cons you discovered while you were learning to use the various Node.js frameworks you've encountered? 🤔

**Comment by Charlotteis** [comment]
I don't actually use Hoodie, I just help maintain it/the community.

My experience with Hapi/Express is fairly minimal. I like Hapi because it's pretty small out of the box.  You have to plug things in to it to make it do other things. So from the very beginning, it's just a basic web server so if that's all you need, your module load is very small.

I also like that it's largely configuration based. Turning settings on and off :)

**Comment by shouston3** [comment]
Because Hapi a framework that is appropriate for the size of the applications Dwyl tends to build.

Express is great for small to medium scale applications, but Hapi is a better choice for medium to large scale applications.

Ideally you would choose your node framework based on the size of your project but switching frameworks when your project grows too large would be costly.

Using Hapi is [occasionally overkill](https://github.com/dwyl/dwyl.github.io) in a Dwyl project, but it does look like a better "one size fits all" choice over express.

Express has better beginner friendly resources, tutorials, and better documentation (and it's source code is much easier to work your way around than Hapi's). [Comparison here](http://stackoverflow.com/questions/30469767/how-do-express-and-hapi-compare-to-each-other).

But I wouldn't want to develop a large scale application with Express because the things that I will eventually need in my express application would either have to be built or sourced from outside of the ecosystem (leading to an opinionated mess of middleware), whereas Hapi would have what you need either out of the box or in it's Ecosystem.

However, one thing that I think should be considered when deciding on Hapi for a framework is that if Hapi is someones first node framework, without enough direction, the overwhelming documentation can lead to them not reading any of it and [utilising very little of what the api has to offer](https://github.com/cul-2016/quiz/tree/dc7b3bbedfb1fc015657dfdc8d20f1d0177153a4/server). Whereas people are far most likely to read documentation when there is less of it and therefore make a more extensive use of an api and write better code.

**Comment by nelsonic** [comment]
Hapi is/was good and it served us well. 🎉 

We've been using Phoenix https://github.com/dwyl/learn-phoenix-framework
for _all_ our new projects and we've been _delighted_ with it. 😍
