### ISSUE TITLE
How should we be architecturing our Phoenix and Elm applications?

### ISSUE THREAD

**Issue by samhstn** [dwyl/technology-stack#47]
I feel broadly these two options make the most sense as to how we should be using these technologies together:

### Option 1: Single page application
[Example backend here](https://github.com/bigardone/phoenix-and-elm/blob/master/web/router.ex)
We serve up one html and js file.
Our backend has only an api interface for our front end.
We will utilise elm's inbuilt routing.
We wont use any of phoenix's inbuilt templating.

### Option 2: Phoenix templating
Each view will be far more independent
We will decide weather to use Phoenix's templating or Elm depending on a view's complexity.
For static view's we can serve up a templated html file
For more interactive views we can serve up an Elm SPA.

Option 1 seems simpler and more familiar
Option 2 seems faster and should offer more control

I understand that deciding on one of these options will probably be project dependent, but in general which architecture should we be looking to use?

**Comment by jackcarlisle** [comment]
@nelsonic would it be possible to have a chat with you at some stage today about this?

**Comment by nelsonic** [comment]
Hi @shouston3 apologies for not replying sooner ... 
my _strong_ preference is for server-side rendering with client-side enhancement.
it's _much_ faster for pages to load on all devices (_both initial time-to-paint and general interaction_)
When a _specific enhancement_ is required we build it with Elm.
Examples of this could include:
+ Offline functionality using PWA techniques
+ Real-time updates without page refresh
+ auto-saving a form to avoid losing data

All Elm components should built independently developed/tested/documented.

**Comment by MartinKavik** [comment]
Hi,
I'm experimenting with this stack: 
- Elm + Tachyons   ([MartinKavik/tachyons-elm-ui-example](https://github.com/MartinKavik/tachyons-elm-ui-example))
- Elixir (maybe someday [Elmchemy](https://github.com/wende/elmchemy) as an alternative) + Phoenix + PostgreSQL
- [Dokku](http://dokku.viewdocs.io/dokku/) (Heroku alternative for testing), maybe [Flynn](https://flynn.io/) (for production) + [Vultr](https://www.vultr.com/) + Amazon S3
- GraphQL: [absinthe-graphql.org](http://absinthe-graphql.org/) + [elm-graphql](https://github.com/jamesmacaulay/elm-graphql)

---

There are some articles with reasons why SPA is better than server-side rendering (e.g. [article 1](https://medium.com/@balint_sera/on-the-separation-of-front-end-and-backend-7a0809b42820), [article 2](https://www.quora.com/Why-does-it-make-sense-to-separate-front-end-from-back-end)..), but I like the idea of separate repos for frontend and backend because:

- It will be easier to develop mobile app (see [elm-native-ui](https://github.com/ohanhi/elm-native-ui)) with existing API server
- It is possible to use GraphQL - it's imho a little bit self-documentating and has many more advantages
- It's easier to setup buildpacks for Heroku / Dokku / Flynn
- There is no template system (only pure Elm & Elixir)
- FE and BE developers can focus only on their specific problems + no more "task ping-pong" between these groups during debugging templates
- It's possible to use specific dev environment (configs, servers, IDEs) for Elm or Elixir, resp. it's not necessary to create  a custom building pipeline for Elixir and Elm
- Some apps don't need (custom) BE + it's nice to write prototypes with [graphcms](https://graphcms.com/) or [graph.cool](https://www.graph.cool/) 
- I don't like to wait for a whole page refresh on a mobile browser when I switch pages

@nelsonic:

**A)**
So could you, please, add more pros of server-side rendering or cons of SPA - I want to see problem from other perspective and learn something new. 

---

**B)**
> All Elm components should built independently developed/tested/documented.

Do you use some best practices / patterns, how to write components with Elm (and Tachyons)?
*(Maybe a question to a new issue)*

---

Thank you very much, have a nice weekend.

P.S. If you are interested, I can write some tutorials how to setup Dokku (and Flynn) + Vultr + Gitlab (maybe Github?) + PostgreSQL with autodeploy when I have some free time.

**Comment by nelsonic** [comment]
https://github.com/dwyl/phoenix-elm-starter
