### ISSUE TITLE
Nice way to get environment variables into PATH

### ISSUE THREAD

**Issue by shouston3** [dwyl/technology-stack#50]
In node we had [env2](https://github.com/dwyl/env2) and stored them in an `.env` file.

How and where should we store them with the new stack?

The best I could find was this: https://github.com/avdi/dotenv_elixir, but was a bit put off by the warning at the top.

**Comment by nelsonic** [comment]
@shouston3 yeah, https://github.com/avdi/dotenv_elixir is a bit "hacky".
If you have time to do a bit more research, go for it. 
@barisbalic (_organiser of Elixir London Meetup and all-round awesome dude!_) might be able to help point you in a good direction. 😉

**Comment by barisbalic** [comment]
Hey @shouston3 / @nelsonic,

Unfortunately not, I've not used any kind of env var management in Elixir, there's been a few around, `Flasked` was the last one I remember looking at.  If you're just looking to avoid the inconvenience of typing them out every time, then I would put a bunch of `exports` in a file and just run that file when you want to work on that project rather than incorporate some half finished project into your toolchain.

Sorry it wasn't that useful :(

**Comment by shouston3** [comment]
I've found adding my environment variables to my `.bashrc`/`.zshrc` (some file that runs on startup) file to be the best solution to this

**Comment by nelsonic** [comment]
@shouston3 provided you only have one set of variables with a specific name, 
this is a good solution. 😉 
as recommended in: https://github.com/dwyl/learn-phoenix-framework/blob/984c9ebea7869e9940ca69722160d887f750c355/production-deployment.md#162-edit-your-profile-file-on-azure-instance-to-set-tcp-port-for-phoenix 👍
