### ISSUE TITLE
A person who already knows javascript should learn flutter or python ?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/technology-stack#82]
I was thinking about programming languages that are now used in the market or in large companies and both Dart, javascript or even python are used in large companies so how do we know which to choose ?

**Comment by nelsonic** [comment]
@miguelmartins17 this is a good question and the answer is: "it depends". 

It depends on what you want to _build_. (_e.g: a mobile app, a game, an e-commerce site, chat app, etc._)
If you have a particular company in mind that you want to work for, what is their technology stack?
e.g: @dwyl we are using **`Elixir`** . So that would be a good language to learn. 
You can always find out what tech a "big" company is using by looking them up on [https://stackshare.io](https://stackshare.io/stacks)
e.g: Twitch (_the game streaming platform_) has the following stack: https://stackshare.io/twitch/twitch
![image](https://user-images.githubusercontent.com/194400/72210896-f3acbe80-34b9-11ea-9f86-281a31b0cade.png)

Another great way of finding out what tech a company uses is looking up their "Jobs" page. e.g: 
https://www.twitch.tv/jobs/#jobs
![image](https://user-images.githubusercontent.com/194400/72210913-1d65e580-34ba-11ea-949d-f256754df5a0.png)

https://boards.greenhouse.io/twitch/jobs/4491808002
![image](https://user-images.githubusercontent.com/194400/72210923-3bcbe100-34ba-11ea-8c93-6c4a499abe93.png)
In this case the _first_ requirement is: "Bachelor’s degree or above in Computer Science or related field" ... 🙄 

> When I _first_ got into software dev in 2009, _most_ jobs required a degree in Computer Science.
> That is _gradually_ changing, but it's still fairly normal. 
> What you want is to find a company (_e.g: @dwyl_) that does _not_ require a University Degree and work _really_ hard to learn as much as you can as _fast_ as you can so that you can build a _great_ product. 
> Having the _experience_ of building a great product is more valuable than any University Degree.
> Having _communication_ skills (_speaking, writing,  presenting ideas and teamwork_) is _way_ more valuable than any qualification. 

If you have a clear idea of what you want to build then you just google various keywords and/or questions until you find the appropriate technology for the _area_ you want to build in.
For example, imagine you wanted to build a chat system for games, you would discover that the backend of the most popular _existing_ chat system for gamers (Discord) is built with **`Elixir`** https://en.wikipedia.org/wiki/Discord_(software) so you could ask _why_ they use Elixir. 
e.g: ask a question on HackerNews: https://news.ycombinator.com/ask

In _your_ case it's pretty clear which programming language to focus on for the next few weeks/months: Dart https://github.com/dwyl/learn-dart and Flutter https://github.com/dwyl/learn-flutter. 
After we (@dwyl) have shipped the @dwyl app https://github.com/dwyl/app to the iOS App Store, Google Play Store and have received feedback from people _using_ the App, I would suggest you learn **`Python`** because it's very versatile. We will have a decent Python tutorial in the next few months which you will be able to review and contribute to.

**Comment by nelsonic** [comment]
Closing as this question is not about the @dwyl tech stack; more of a personal learning question.
Hopefully the answer gives the OP enough insight to make a decision as to what to learn. 👍
