### ISSUE TITLE
Forest Application

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/technology-stack#83]
Have you ever heard of the "Forest" application?

![Screen Shot 2020-01-21 at 12 24 50](https://user-images.githubusercontent.com/27420533/72804928-9945f780-3c49-11ea-80be-e0838559ca35.png)

Basically it is an application made for those who want to stay focused on a certain task, the user chooses the time he wants to be focused and plants a tree over the days whenever he stays focused the tree grows if he leaves the application the tree dies.

![Screen Shot 2020-01-21 at 12 23 58](https://user-images.githubusercontent.com/27420533/72804937-9ea34200-3c49-11ea-80b3-320ed65e0158.png)

I found it very interesting because it makes that when you are using that app in the cell phone for example when you activate it you can only be with the screen in that app and forces people addicted to the cell phone to only use that app at the moment of concentration.
It is not my main goal but I found it interesting to share this information with you.

**Comment by nelsonic** [comment]
@miguelmartins17 we are aware of Forrest.
It is a good _single-purpose_ app with a simple UI/UX. 
There are quite a few _similar_ apps in various forms both online and in App stores.
Countdown timers are a _feature_ of our App.
But we feel that in order to help us be more effective, quite a lot more functionality is needed.
